In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import datetime as dat
import matplotlib as mplt
import datetime as dt
%matplotlib inline
sns.set()

In [2]:
auctions = pd.read_csv("data/auctions.csv", dtype={'date': 'str',
                                                   'device_id': 'category', 'ref_type_id': 'category',
                                                   'source_id':'category'}, parse_dates = ['date'])
auctions.head(5)

                        date            device_id ref_type_id source_id
0 2019-04-23 18:58:00.842116  2564673204772915246           1         0
1 2019-04-23 18:58:01.530771  4441121667607578179           7         0
2 2019-04-23 18:58:01.767562  7721769811471055264           1         0
3 2019-04-23 18:58:02.363468  6416039086842158968           1         0
4 2019-04-23 18:58:02.397559  1258642015983312729           1         0

In [4]:
auctions['mean_hour']=auctions['date'].dt.hour
auctions['std_hour']=auctions['date'].dt.hour
auctions=auctions.sort_values(by='date')

In [5]:
serie=auctions.groupby('device_id').cumcount()
serie=serie.to_list()

In [6]:
auctions['entradas_previas']=serie
auctions.head()

,date,device_id,ref_type_id,source_id,mean_hour,std_hour,entradas_previas
10129864,2019-04-18 00:00:00.015050,1826643666390887030,7,0,0,0,0
25285906,2019-04-18 00:00:00.029014,7037174172278258682,1,0,0,0,0
3946062,2019-04-18 00:00:00.057540,3392065368947589877,1,1,0,0,0
3946063,2019-04-18 00:00:00.126828,1228982273563226229,1,1,0,0,0
24607726,2019-04-18 00:00:00.132510,4123059034628125459,1,8,0,0,0

In [9]:
auctions['mean_hour']=auctions['mean_hour'].expanding(2).mean()
auctions['std_hour']=auctions['std_hour'].expanding(2).std()

In [10]:
auctions.head(5)

,date,device_id,ref_type_id,source_id,mean_hour,std_hour,entradas_previas
10129864,2019-04-18 00:00:00.015050,1826643666390887030,7,0,NaN,NaN,0
25285906,2019-04-18 00:00:00.029014,7037174172278258682,1,0,0.0,0.0,0
3946062,2019-04-18 00:00:00.057540,3392065368947589877,1,1,0.0,0.0,0
3946063,2019-04-18 00:00:00.126828,1228982273563226229,1,1,0.0,0.0,0
24607726,2019-04-18 00:00:00.132510,4123059034628125459,1,8,0.0,0.0,0

In [11]:
fecha_minima=pd.to_datetime('2019-04-18 00:00:00')
fecha_minima
fecha_tope=pd.to_datetime('2019-04-21 00:00:00')
auctions_ventana1=auctions.loc[auctions['date']<fecha_tope].copy(deep=False)
#la division es para pasar la diferencia de tiempso de timedelta a float de dias
auctions_ventana1['tiempo_hasta_aparicion']=(auctions_ventana1['date']-fecha_minima)/ np.timedelta64(24, 'h')

auctions_ventana1.head(25)
#auctions_ventana1['date'].max()

,date,device_id,ref_type_id,source_id,mean_hour,std_hour,entradas_previas,tiempo_hasta_aparicion
10129864,2019-04-18 00:00:00.015050,1826643666390887030,7,0,NaN,NaN,0,1.741898e-07
25285906,2019-04-18 00:00:00.029014,7037174172278258682,1,0,0.0,0.0,0,3.358102e-07
3946062,2019-04-18 00:00:00.057540,3392065368947589877,1,1,0.0,0.0,0,6.659722e-07
3946063,2019-04-18 00:00:00.126828,1228982273563226229,1,1,0.0,0.0,0,1.467917e-06
24607726,2019-04-18 00:00:00.132510,4123059034628125459,1,8,0.0,0.0,0,1.533681e-06
11820552,2019-04-18 00:00:00.154022,2544156497510885464,1,1,0.0,0.0,0,1.782662e-06
44538105,2019-04-18 00:00:00.167606,8523620031586497559,1,1,0.0,0.0,0,1.939884e-06
4953159,2019-04-18 00:00:00.176600,3926687473682441392,1,1,0.0,0.0,0,2.043981e-06
11812696,2019-04-18 00:00:00.191287,528082274254399315,1,1,0.0,0.0,0,2.213970e-06
11820553,2019-04-18 00:00:00.217645,8160556786289359332,7,1,0.0,0.0,0,2.519039e-06
47080629,2019-04-18 00:00:00.219200,2844535553398493162,1,1,0.0,0.0,0,2.537037e-06
44517641,2019-04-18 00:00:00.225600,1680272311925142702,1,1,0.0,0.0,0,2.611111e-06
44538106,2019-04-18 00:00:00.231719,7508214929604895080,1,1,0.0,0.0,0,2.681933e-06
3434618,2019-04-18 00:00:00.233441,3926237048471091695,1,1,0.0,0.0,0,2.701863e-06
44514683,2019-04-18 00:00:00.241021,5802277733017057132,1,1,0.0,0.0,0,2.789595e-06
44514684,2019-04-18 00:00:00.259283,3651814472131322640,1,1,0.0,0.0,0,3.000961e-06
44504337,2019-04-18 00:00:00.292937,3965552861693715909,1,1,0.0,0.0,0,3.390475e-06
16344775,2019-04-18 00:00:00.294466,3070948202665858642,1,0,0.0,0.0,0,3.408171e-06
10129865,2019-04-18 00:00:00.299745,9087325953285418021,7,0,0.0,0.0,0,3.469271e-06
16188706,2019-04-18 00:00:00.306234,1819974464797805789,1,3,0.0,0.0,0,3.544375e-06
44538107,2019-04-18 00:00:00.309708,5910141895954932407,1,1,0.0,0.0,0,3.584583e-06
20481863,2019-04-18 00:00:00.319542,3504225602898030913,1,0,0.0,0.0,0,3.698403e-06
16344776,2019-04-18 00:00:00.358183,7181749374516241024,1,0,0.0,0.0,0,4.145637e-06
16735299,2019-04-18 00:00:00.358382,2053845849512280922,1,3,0.0,0.0,0,4.147940e-06
11798280,2019-04-18 00:00:00.363428,1680272311925142702,1,1,0.0,0.0,1,4.206343e-06

In [13]:
auctions_ventana1_reducido=auctions_ventana1.groupby(['device_id']).agg({"date" : min,\
                                                                         "std_hour" : "first",\
                                                                         "mean_hour" : "first",\
                                                                         'tiempo_hasta_aparicion':"min",\
                                                                        'entradas_previas':min})\
                                                                            .reset_index('device_id')
#entradas previas no se debe usar para predecir en esta ventana, sino para                
auctions_ventana1_reducido=auctions_ventana1_reducido.dropna()

In [14]:
fecha_minima=pd.to_datetime('2019-04-21 00:00:00')
fecha_tope=pd.to_datetime('2019-04-24 00:00:00')

auctions_ventana2=auctions.loc[((auctions['date']>fecha_minima) & (auctions['date']<fecha_tope) )].copy(deep=False)
#la division es para pasar la diferencia de tiempso de timedelta a float de dias
auctions_ventana2['tiempo_hasta_aparicion']=(auctions_ventana2['date']-fecha_minima)/ np.timedelta64(24, 'h')

In [15]:
auctions_ventana2.head()

,date,device_id,ref_type_id,source_id,mean_hour,std_hour,entradas_previas,tiempo_hasta_aparicion
24020961,2019-04-21 00:00:00.004920,5733927591955330573,1,1,11.793843,7.809312,794,5.694444e-08
7177371,2019-04-21 00:00:00.007056,8906329411852863929,1,3,11.793843,7.809312,579,8.166667e-08
22059193,2019-04-21 00:00:00.017098,4823921476577985805,1,1,11.793842,7.809312,352,1.978935e-07
13270775,2019-04-21 00:00:00.032361,1118383901220956279,1,3,11.793841,7.809312,161,3.745486e-07
9429524,2019-04-21 00:00:00.042073,2052804935692491509,1,0,11.793840,7.809313,42,4.869560e-07

In [17]:
auctions_ventana2['dia_desvio_std']=auctions_ventana2['date'].dt.day
auctions_ventana2_reducido=auctions_ventana2.groupby(['device_id']).agg({"date" : min,\
                                                                         "std_hour" : "first",\
                                                                         "mean_hour" : "first",\
                                                                         'tiempo_hasta_aparicion':"min",\
                                                                        'entradas_previas':min})\
                                                                            .reset_index('device_id')
#entradas previas no se debe usar para predecir en esta ventana, sino para                
auctions_ventana2_reducido=auctions_ventana2_reducido.dropna()
auctions_ventana2_reducido.head()

,device_id,date,std_hour,mean_hour,tiempo_hasta_aparicion,entradas_previas
0,100033926124811452,2019-04-23 03:10:50.587009,7.924889,11.307374,2.132530,0.0
1,1000400432115255220,2019-04-21 02:41:03.200096,7.973811,11.252396,0.111843,1.0
2,1001123163431776865,2019-04-21 01:41:47.707241,7.937342,11.438620,0.070691,68.0
3,1001144380199556647,2019-04-21 15:12:55.733409,7.754734,10.781650,0.633978,78.0
4,1001358436431521709,2019-04-21 03:39:07.387349,7.984042,11.096513,0.152169,0.0

In [18]:
fecha_minima=pd.to_datetime('2019-04-22 00:00:00')
fecha_tope=pd.to_datetime('2019-04-25 00:00:00')

auctions_ventana3=auctions.loc[((auctions['date']>fecha_minima) & (auctions['date']<fecha_tope) )].copy(deep=False)
#la division es para pasar la diferencia de tiempso de timedelta a float de dias
auctions_ventana3['tiempo_hasta_aparicion']=(auctions_ventana2['date']-fecha_minima)/ np.timedelta64(24, 'h')
auctions_ventana3['dia_mean']=auctions_ventana3['date'].dt.day
auctions_ventana3['dia_desvio_std']=auctions_ventana3['date'].dt.day
auctions_ventana3.head(25)
auctions_ventana3_reducido=auctions_ventana3.groupby(['device_id']).agg({"date" : min,\
                                                                         "std_hour" : "first",\
                                                                         "mean_hour" : "first",\
                                                                         'tiempo_hasta_aparicion':"min",\
                                                                        'entradas_previas':min})\
                                                                            .reset_index('device_id')
#entradas previas no se debe usar para predecir en esta ventana, sino para                
auctions_ventana3_reducido=auctions_ventana3_reducido.dropna()

In [19]:
fecha_minima=pd.to_datetime('2019-04-23 00:00:00')
fecha_tope=pd.to_datetime('2019-04-26 00:00:00')

auctions_ventana4=auctions.loc[((auctions['date']>fecha_minima) & (auctions['date']<fecha_tope) )].copy(deep=False)
#la division es para pasar la diferencia de tiempso de timedelta a float de dias
auctions_ventana4['tiempo_hasta_aparicion']=(auctions_ventana2['date']-fecha_minima)/ np.timedelta64(24, 'h')
auctions_ventana4['dia_mean']=auctions_ventana4['date'].dt.day
auctions_ventana4['dia_desvio_std']=auctions_ventana4['date'].dt.day
auctions_ventana4.head(25)
auctions_ventana4_reducido=auctions_ventana4.groupby(['device_id']).agg({"date" : min,\
                                                                         "std_hour" : "first",\
                                                                         "mean_hour" : "first",\
                                                                         'tiempo_hasta_aparicion':"min",\
                                                                        'entradas_previas':min})\
                                                                            .reset_index('device_id')
#entradas previas no se debe usar para predecir en esta ventana, sino para                
auctions_ventana4_reducido=auctions_ventana4_reducido.dropna()

In [20]:
fecha_minima=pd.to_datetime('2019-04-24 00:00:00')
fecha_tope=pd.to_datetime('2019-04-27 00:00:00')

auctions_ventana5=auctions.loc[((auctions['date']>fecha_minima) & (auctions['date']<fecha_tope) )].copy(deep=False)
#la division es para pasar la diferencia de tiempso de timedelta a float de dias
auctions_ventana5['tiempo_hasta_aparicion']=(auctions_ventana2['date']-fecha_minima)/ np.timedelta64(24, 'h')
auctions_ventana5['dia_mean']=auctions_ventana5['date'].dt.day
auctions_ventana5['dia_desvio_std']=auctions_ventana5['date'].dt.day
auctions_ventana5.head(25)
auctions_ventana5_reducido=auctions_ventana1.groupby(['device_id']).agg({"date" : min,\
                                                                         "std_hour" : "first",\
                                                                         "mean_hour" : "first",\
                                                                         'tiempo_hasta_aparicion':"min",\
                                                                        'entradas_previas':min})\
                                                                            .reset_index('device_id')
#entradas previas no se debe usar para predecir en esta ventana, sino para                
auctions_ventana5_reducido=auctions_ventana5_reducido.dropna()

In [21]:
installs = pd.read_csv("data/installs.csv", dtype={'auction_type_id': 'float64', 'country': 'int64', 'date': 'str',
                                                   'device_id': 'int64', 'platform':'int64', 'ref_type_id': 'int64',
                                                   'source_id':'int64','ref_hash':'category' }, parse_dates = ['created'],low_memory=False)

installs.head(5)

,created,application_id,ref_type,ref_hash,click_hash,attributed,implicit,device_countrycode,device_brand,device_model,session_user_agent,user_agent,event_uuid,kind,wifi,trans_id,ip_address,device_language
0,2019-04-24 06:23:29.495,1,1494519392962156891,4716708407362582887,NaN,False,True,6287817205707153877,NaN,3.739127e+17,adjust.com,NaN,79837499-2f2a-4605-a663-e322f759424f,app_open,NaN,NaN,4243443387795468703,3.301378e+18
1,2019-04-24 02:06:01.032,1,1494519392962156891,7143568733100935872,NaN,False,False,6287817205707153877,NaN,7.805539e+18,adjust.com,NaN,NaN,NaN,NaN,NaN,4724288679627032761,3.301378e+18
2,2019-04-20 10:15:36.274,1,1494519392962156891,5230323462636548010,NaN,False,True,6287817205707153877,NaN,8.355496e+18,adjust.com,NaN,dda99e3c-9c4b-487d-891c-79f0a02cb4a8,app_open,NaN,NaN,8291809486355890410,4.060930e+18
3,2019-04-20 21:56:47.151,1,1494519392962156891,5097163995161606833,NaN,False,True,6287817205707153877,NaN,2.355772e+18,adjust.com,NaN,7010c3ce-0fcf-46c6-9be8-374cc0e20af4,app_open,NaN,NaN,4006811922873399949,3.301378e+18
4,2019-04-20 22:40:41.239,1,1494519392962156891,6328027616411983332,NaN,False,False,6287817205707153877,NaN,6.156971e+18,adjust.com,NaN,NaN,NaN,NaN,NaN,3386455054590810771,3.301378e+18

In [22]:
auctions_ventana1_con_installs=auctions_ventana1_reducido.merge(installs,how='left',left_on='device_id',right_on='ref_hash')

In [25]:
fecha_minima=pd.to_datetime('2019-04-20 00:00:00')
fecha_tope=pd.to_datetime('2019-04-23 00:00:00')


auctions_ventana1_con_installs['tiempo_hasta_instalacion']=(auctions_ventana1_con_installs['created']-fecha_minima)/ np.timedelta64(24, 'h')


auctions_ventana1_reducido=auctions_ventana1_con_installs.groupby(['device_id']).agg({"mean_hour" : min,\
                                                                         "date" : min,\
                                                                         "std_hour" : "min",\
                                                                         'tiempo_hasta_aparicion':"min",\
                                                                        'entradas_previas':min
                                                                        ,'tiempo_hasta_instalacion':"min"})\
                                                                            .reset_index('device_id')

In [26]:
auctions_ventana1_reducido[['dia_mean','tiempo_hasta_aparicion','dia_desvio_std','tiempo_hasta_instalacion']]=auctions_ventana1_reducido[['dia_mean','tiempo_hasta_aparicion','dia_desvio_std','tiempo_hasta_instalacion']].fillna(np.inf)
auctions_ventana1_reducido['entradas_previas']=auctions_ventana1_reducido['entradas_previas'].fillna(0)
auctions_ventana1_reducido.head()

KeyError: "['dia_mean', 'dia_desvio_std'] not in index"

In [27]:
fecha_minima=pd.to_datetime('2019-04-21 00:00:00')
fecha_tope=pd.to_datetime('2019-04-24 00:00:00')
auctions_ventana2_con_installs=auctions_ventana2_reducido.merge(installs,how='left',left_on='device_id',right_on='ref_hash')

auctions_ventana2_con_installs['tiempo_hasta_instalacion']=(auctions_ventana2_con_installs['created']-fecha_minima)/ np.timedelta64(24, 'h')


auctions_ventana2_reducido=auctions_ventana2_con_installs.groupby(['device_id']).agg({"mean_hour" : min,\
                                                                         "date" : min,\
                                                                         "std_hour" : "min",\
                                                                         'tiempo_hasta_aparicion':"min",\
                                                                        'entradas_previas':min
                                                                        ,'tiempo_hasta_instalacion':"min"})\
                                                                            .reset_index('device_id')
auctions_ventana2_reducido[['dia_mean','tiempo_hasta_aparicion','dia_desvio_std','tiempo_hasta_instalacion']]=auctions_ventana2_reducido[['dia_mean','tiempo_hasta_aparicion','dia_desvio_std','tiempo_hasta_instalacion']].fillna(np.inf)
auctions_ventana2_reducido['entradas_previas']=auctions_ventana2_reducido['entradas_previas'].fillna(0)
auctions_ventana2_reducido.head()

KeyError: "['dia_mean', 'dia_desvio_std'] not in index"

In [ ]:
fecha_minima=pd.to_datetime('2019-04-22 00:00:00')
fecha_tope=pd.to_datetime('2019-04-25 00:00:00')
auctions_ventana3_con_installs=auctions_ventana3_reducido.merge(installs,how='left',left_on='device_id',right_on='ref_hash')

auctions_ventana3_con_installs['tiempo_hasta_instalacion']=(auctions_ventana3_con_installs['created']-fecha_minima)/ np.timedelta64(24, 'h')


auctions_ventana3_reducido=auctions_ventana3_con_installs.groupby(['device_id']).agg({"mean_hour" : min,\
                                                                         "date" : min,\
                                                                         "mean_std" : "min",\
                                                                         'tiempo_hasta_aparicion':"min",\
                                                                        'entradas_previas':min
                                                                        ,'tiempo_hasta_instalacion':"min"})\
                                                                            .reset_index('device_id')
auctions_ventana3_reducido[['dia_mean','tiempo_hasta_aparicion','dia_desvio_std','tiempo_hasta_instalacion']]=auctions_ventana3_reducido[['dia_mean','tiempo_hasta_aparicion','dia_desvio_std','tiempo_hasta_instalacion']].fillna(np.inf)
auctions_ventana3_reducido['entradas_previas']=auctions_ventana3_reducido['entradas_previas'].fillna(0)
auctions_ventana3_reducido.head()

In [ ]:
fecha_minima=pd.to_datetime('2019-04-23 00:00:00')
fecha_tope=pd.to_datetime('2019-04-26 00:00:00')
auctions_ventana4_con_installs=auctions_ventana4_reducido.merge(installs,how='left',left_on='device_id',right_on='ref_hash')

auctions_ventana4_con_installs['tiempo_hasta_instalacion']=(auctions_ventana4_con_installs['created']-fecha_minima)/ np.timedelta64(24, 'h')


auctions_ventana4_reducido=auctions_ventana3_con_installs.groupby(['device_id']).agg({"mean_hour" : min,\
                                                                         "date" : min,\
                                                                         "std_hour" : "min",\
                                                                         'tiempo_hasta_aparicion':"min",\
                                                                        'entradas_previas':min
                                                                        ,'tiempo_hasta_instalacion':"min"})\
                                                                            .reset_index('device_id')
auctions_ventana4_reducido[['dia_mean','tiempo_hasta_aparicion','dia_desvio_std','tiempo_hasta_instalacion']]=auctions_ventana4_reducido[['dia_mean','tiempo_hasta_aparicion','dia_desvio_std','tiempo_hasta_instalacion']].fillna(np.inf)
auctions_ventana4_reducido['entradas_previas']=auctions_ventana4_reducido['entradas_previas'].fillna(0)
auctions_ventana4_reducido.head()