In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import datetime as dat
import matplotlib as mplt
import datetime as dt
%matplotlib inline
sns.set()

In [2]:
auctions = pd.read_csv("data/auctions.csv", dtype={'date': 'str',
                                                   'device_id': 'category', 'ref_type_id': 'category',
                                                   'source_id':'category'}, parse_dates = ['date'])
auctions.head(5)

                        date            device_id ref_type_id source_id
0 2019-04-23 18:58:00.842116  2564673204772915246           1         0
1 2019-04-23 18:58:01.530771  4441121667607578179           7         0
2 2019-04-23 18:58:01.767562  7721769811471055264           1         0
3 2019-04-23 18:58:02.363468  6416039086842158968           1         0
4 2019-04-23 18:58:02.397559  1258642015983312729           1         0

In [3]:
auctions=auctions.sort_values(by='date')

In [4]:
serie=auctions.groupby('device_id').cumcount()
serie=serie.to_list()

In [5]:
auctions['entradas_previas']=serie

In [9]:
fecha_minima=pd.to_datetime('2019-04-18 00:00:00')
fecha_minima
fecha_tope=pd.to_datetime('2019-04-21 00:00:00')
auctions_ventana1=auctions.loc[auctions['date']<fecha_tope].copy(deep=False)
#la division es para pasar la diferencia de tiempso de timedelta a float de dias
auctions_ventana1['tiempo_hasta_aparicion']=(auctions_ventana1['date']-fecha_minima)/ np.timedelta64(24, 'h')
auctions_ventana1['dia_mean']=auctions_ventana1['date'].dt.day
auctions_ventana1['dia_desvio_std']=auctions_ventana1['date'].dt.day
auctions_ventana1.head(25)
#auctions_ventana1['date'].max()

,date,device_id,ref_type_id,source_id,entradas_previas,tiempo_hasta_aparicion,dia_mean,dia_desvio_std
10129864,2019-04-18 00:00:00.015050,1826643666390887030,7,0,0,1.741898e-07,18,18
25285906,2019-04-18 00:00:00.029014,7037174172278258682,1,0,0,3.358102e-07,18,18
3946062,2019-04-18 00:00:00.057540,3392065368947589877,1,1,0,6.659722e-07,18,18
3946063,2019-04-18 00:00:00.126828,1228982273563226229,1,1,0,1.467917e-06,18,18
24607726,2019-04-18 00:00:00.132510,4123059034628125459,1,8,0,1.533681e-06,18,18
11820552,2019-04-18 00:00:00.154022,2544156497510885464,1,1,0,1.782662e-06,18,18
44538105,2019-04-18 00:00:00.167606,8523620031586497559,1,1,0,1.939884e-06,18,18
4953159,2019-04-18 00:00:00.176600,3926687473682441392,1,1,0,2.043981e-06,18,18
11812696,2019-04-18 00:00:00.191287,528082274254399315,1,1,0,2.213970e-06,18,18
11820553,2019-04-18 00:00:00.217645,8160556786289359332,7,1,0,2.519039e-06,18,18
47080629,2019-04-18 00:00:00.219200,2844535553398493162,1,1,0,2.537037e-06,18,18
44517641,2019-04-18 00:00:00.225600,1680272311925142702,1,1,0,2.611111e-06,18,18
44538106,2019-04-18 00:00:00.231719,7508214929604895080,1,1,0,2.681933e-06,18,18
3434618,2019-04-18 00:00:00.233441,3926237048471091695,1,1,0,2.701863e-06,18,18
44514683,2019-04-18 00:00:00.241021,5802277733017057132,1,1,0,2.789595e-06,18,18
44514684,2019-04-18 00:00:00.259283,3651814472131322640,1,1,0,3.000961e-06,18,18
44504337,2019-04-18 00:00:00.292937,3965552861693715909,1,1,0,3.390475e-06,18,18
16344775,2019-04-18 00:00:00.294466,3070948202665858642,1,0,0,3.408171e-06,18,18
10129865,2019-04-18 00:00:00.299745,9087325953285418021,7,0,0,3.469271e-06,18,18
16188706,2019-04-18 00:00:00.306234,1819974464797805789,1,3,0,3.544375e-06,18,18
44538107,2019-04-18 00:00:00.309708,5910141895954932407,1,1,0,3.584583e-06,18,18
20481863,2019-04-18 00:00:00.319542,3504225602898030913,1,0,0,3.698403e-06,18,18
16344776,2019-04-18 00:00:00.358183,7181749374516241024,1,0,0,4.145637e-06,18,18
16735299,2019-04-18 00:00:00.358382,2053845849512280922,1,3,0,4.147940e-06,18,18
11798280,2019-04-18 00:00:00.363428,1680272311925142702,1,1,1,4.206343e-06,18,18

In [11]:
auctions_ventana1['entradas_previas'].value_counts()

0        318325
1        270109
2        240005
3        218598
4        201923
5        188339
6        176954
7        167217
8        158705
9        151291
10       144761
11       138893
12       133575
13       128646
14       124149
15       120059
16       116228
17       112684
18       109427
19       106302
20       103470
21       100750
22        98105
23        95747
24        93378
25        91157
26        89052
27        87029
28        85110
29        83260
          ...
9974          1
9973          1
9972          1
9963          1
9962          1
9961          1
9990          1
9991          1
9984          1
9985          1
10012         1
10003         1
10002         1
10001         1
10000         1
10007         1
10006         1
10005         1
10004         1
9995          1
9994          1
9993          1
9992          1
9999          1
9998          1
9997          1
9996          1
9987          1
9986          1
10010         1
Name: entradas_previas, Length: 10058, dtype: int64

In [12]:
auctions_ventana1_reducido=auctions_ventana1.groupby(['device_id']).agg({"dia_mean" : np.mean,\
                                                                         "dia_desvio_std" : "std",\
                                                                         'tiempo_hasta_aparicion':"min",\
                                                                        'entradas_previas':min})\
                                                                            .reset_index('device_id')
#entradas previas no se debe usar para predecir en esta ventana, sino para                
auctions_ventana1_reducido.dropna()

,device_id,dia_mean,dia_desvio_std,tiempo_hasta_aparicion,entradas_previas
2,1001123163431776865,19.235294,0.812544,0.016690,0.0
3,1001144380199556647,18.782051,0.783721,0.022885,0.0
5,1001650136929210538,18.910751,0.726559,0.004106,0.0
6,1001893648440705480,18.986301,1.006826,0.068288,0.0
7,1002004782572506858,19.560000,0.690103,0.742676,0.0
8,1002085736203824817,19.500000,0.925820,0.169294,0.0
9,1002447145227437936,18.981818,0.782107,0.000013,0.0
10,1002862509106471090,19.303597,0.686365,0.006661,0.0
11,1003038576428296315,18.000000,0.000000,0.077522,0.0
13,1003855069948308769,19.000000,1.000000,0.237242,0.0
14,1004535879545899547,20.000000,0.000000,2.953942,0.0
17,1004742301877775554,18.000000,0.000000,0.728914,0.0
18,1004800149279553387,18.785985,0.763016,0.000222,0.0
22,100543418029071977,19.750000,0.707107,0.691345,0.0
23,1005862257005415556,18.000000,0.000000,0.285804,0.0
24,1005869594080353226,19.174419,0.722607,0.017741,0.0
25,1006047336388488529,18.722222,0.787081,0.003765,0.0
27,1006635159741148154,19.684211,0.735767,0.646260,0.0
28,1006688297714348969,18.000000,0.000000,0.680028,0.0
29,1006797402765614581,18.155556,0.424026,0.145266,0.0
30,1006847881391189475,19.054054,0.366093,0.673487,0.0
31,1006901992036900768,19.750000,0.500000,1.741617,0.0
32,100694208744052260,19.166667,0.983192,0.548901,0.0
34,1007196251320473224,19.109712,0.785347,0.001339,0.0
35,1007262066891761130,19.900990,0.359794,0.837287,0.0
36,1007421766082572729,18.188679,0.392490,0.111241,0.0
37,1007541311929596576,20.000000,0.000000,2.940484,0.0
39,1007907030089916102,18.947368,0.821645,0.025249,0.0
40,1008202318408878868,19.212121,0.644865,0.641956,0.0
41,1008371923918393253,18.000000,0.000000,0.013174,0.0
...,...,...,...,...,...
474720,5057486785234315759,18.000000,0.000000,0.132515,0.0
474735,5561180458535338156,18.000000,0.000000,0.881212,0.0
474748,6192860240625465338,18.000000,0.000000,0.167628,0.0
474801,7906530039670213736,18.000000,0.000000,0.261016,0.0
474844,1034262093753207250,18.000000,0.000000,0.192513,0.0
474845,1120817971255716291,18.000000,0.000000,0.872021,0.0
474857,199960563493894884,18.000000,0.000000,0.304895,0.0
474871,2644317639370528395,18.000000,0.000000,0.871131,0.0
474874,2997819362696722591,18.000000,0.000000,0.915546,0.0
474878,3047141406537259335,18.000000,0.000000,0.916681,0.0
474889,37685290937963979,18.000000,0.000000,0.296519,0.0
474899,4530030513608044178,18.000000,0.000000,0.873194,0.0
474918,531644748011586703,18.000000,0.000000,0.872422,0.0
474922,5499752944187128492,18.000000,0.000000,0.875841,0.0
474926,5634801009453769286,18.000000,0.000000,0.870869,0.0
474948,6866006940269720533,18.000000,0.000000,0.914703,0.0
474958,7231550014628933730,18.000000,0.000000,0.875198,0.0
474959,7236983271167262655,18.000000,0.000000,0.871372,0.0
474968,7733917092899861970,18.000000,0.000000,0.860639,0.0
474977,8380280198851048069,18.000000,0.000000,0.914306,0.0
475062,5976656623142482399,18.000000,0.000000,0.033985,0.0
475088,7870599210435466794,18.000000,0.000000,0.010535,0.0
475130,2216338258166552557,19.000000,0.000000,1.733537,0.0
475173,5801310484741723711,19.000000,0.000000,1.746665,0.0
475184,6357447127277483663,19.000000,0.000000,1.884695,0.0
475186,6665969962394058665,19.000000,0.000000,1.909269,0.0
475222,8740379183993269006,19.000000,0.000000,1.973594,0.0
475241,2054102885758022477,19.000000,0.000000,1.069699,0.0
475255,3226719842862793017,19.000000,0.000000,1.060195,0.0
475320,8058283318357993885,19.000000,0.000000,1.139032,0.0

In [23]:
fecha_minima=pd.to_datetime('2019-04-21 00:00:00')
fecha_tope=pd.to_datetime('2019-04-24 00:00:00')

auctions_ventana2=auctions.loc[((auctions['date']>fecha_minima) & (auctions['date']<fecha_tope) )].copy(deep=False)
#la division es para pasar la diferencia de tiempso de timedelta a float de dias
auctions_ventana2['tiempo_hasta_aparicion']=(auctions_ventana2['date']-fecha_minima)/ np.timedelta64(24, 'h')
auctions_ventana2['dia_mean']=auctions_ventana2['date'].dt.day
auctions_ventana2['dia_desvio_std']=auctions_ventana2['date'].dt.day
auctions_ventana2_reducido=auctions_ventana2.groupby(['device_id']).agg({"dia_mean" : np.mean,\
                                                                         "dia_desvio_std" : "std",\
                                                                         'tiempo_hasta_aparicion':"min",\
                                                                        'entradas_previas':min})\
                                                                            .reset_index('device_id')
#entradas previas no se debe usar para predecir en esta ventana, sino para                
auctions_ventana2_reducido.dropna()

,device_id,dia_mean,dia_desvio_std,tiempo_hasta_aparicion,entradas_previas
0,100033926124811452,23.000000,0.000000,2.132530,0.0
1,1000400432115255220,21.615385,0.935144,0.111843,1.0
2,1001123163431776865,21.795918,0.785949,0.070691,68.0
3,1001144380199556647,22.016760,0.837833,0.633978,78.0
4,1001358436431521709,21.903226,0.970207,0.152169,0.0
5,1001650136929210538,22.031866,0.830947,0.000563,1479.0
6,1001893648440705480,22.562500,0.500000,1.695995,73.0
7,1002004782572506858,21.970228,0.652248,0.146664,150.0
8,1002085736203824817,22.272727,0.694284,0.047673,8.0
9,1002447145227437936,22.115499,0.813356,0.040113,550.0
10,1002862509106471090,22.347267,0.728389,0.006809,695.0
11,1003038576428296315,23.000000,0.000000,2.253057,17.0
12,1003279313141612495,22.894737,0.315302,1.615052,0.0
13,1003855069948308769,22.370031,0.483552,1.005857,5.0
14,1004535879545899547,23.000000,0.000000,2.945440,3.0
15,1004700862144409340,22.149733,0.357287,1.244064,0.0
16,1004741910852937385,22.837209,0.371340,1.732339,0.0
17,1004742301877775554,22.500000,0.518875,1.779522,4.0
18,1004800149279553387,22.083146,0.636579,0.017838,528.0
19,1005054093755188636,23.000000,0.000000,2.800609,0.0
20,1005228501295042451,22.142857,0.358569,1.014115,1.0
21,1005306798897590259,23.000000,0.000000,2.942633,0.0
22,100543418029071977,22.125000,0.612372,0.121585,8.0
23,1005862257005415556,22.037500,0.753788,0.349630,51.0
24,1005869594080353226,21.823529,0.833473,0.144323,86.0
25,1006047336388488529,21.327935,0.663929,0.108529,54.0
26,1006386733075661409,22.402062,0.613489,0.953585,0.0
27,1006635159741148154,21.222535,0.550859,0.009283,57.0
28,1006688297714348969,22.934866,0.247236,1.984624,7.0
29,1006797402765614581,21.812500,0.990030,0.057348,45.0
...,...,...,...,...,...
472789,8463819022493405594,22.000000,0.000000,1.910634,0.0
472815,120066053544397299,22.000000,0.000000,1.101404,0.0
472822,1675465894456303904,22.000000,0.000000,1.296024,0.0
472825,1808914933107929388,22.000000,0.000000,1.115675,0.0
472848,3237282560961568132,22.000000,0.000000,1.462977,0.0
472857,4480418618087428655,22.000000,0.000000,1.777397,0.0
472867,5162917905135447805,22.000000,0.000000,1.569112,0.0
473382,1091911987149783821,23.000000,0.000000,2.246217,0.0
473428,4389700610314188729,23.000000,0.000000,2.802441,0.0
473430,4448465669266609869,23.000000,0.000000,2.112555,0.0
473480,817713062634440208,23.000000,0.000000,2.809429,0.0
473504,2154190506951957785,21.000000,0.000000,0.815146,0.0
473528,3673380501301167226,23.000000,0.000000,2.122695,0.0
473536,4174230555993324923,21.000000,0.000000,0.817787,0.0
473561,6338388692042622627,23.000000,0.000000,2.686098,0.0
473593,8354412565619928900,21.000000,0.000000,0.917447,0.0
473630,2875991245911166305,21.000000,0.000000,0.691637,0.0
473684,7046018604591284421,22.000000,0.000000,1.884480,0.0
473720,1127100346799212752,22.000000,0.000000,1.032365,0.0
473727,1311021507745710058,22.000000,0.000000,1.080603,0.0
473737,1944593511424495249,22.000000,0.000000,1.653106,0.0
473743,2519711926042368334,22.000000,0.000000,1.030668,0.0
473747,2733151881632131754,22.000000,0.000000,1.429489,0.0
473784,4689245893119354457,22.000000,0.000000,1.850088,0.0
473801,5717468255227731540,22.000000,0.000000,1.010283,0.0
473816,6532569181386617584,22.000000,0.000000,1.197555,0.0
475059,5811542591767694512,23.000000,0.000000,2.519153,0.0
475118,1525572494050423197,23.000000,0.000000,2.033734,0.0
475129,2196302881459117962,23.000000,0.000000,2.106825,0.0
475148,3927025339438948829,23.000000,0.000000,2.205814,0.0

In [16]:
auctions_ventana2_reducido=auctions_ventana2.groupby(['device_id']).agg({"dia_mean" : np.mean,\
                                                                         "dia_desvio_std" : "std",\
                                                                         'tiempo_hasta_aparicion':"min",\
                                                                        'entradas_previas':min})\
                                                                            .reset_index('device_id')
#entradas previas no se debe usar para predecir en esta ventana, sino para                
auctions_ventana2_reducido.dropna()

,device_id,dia_mean,dia_desvio_std,tiempo_hasta_aparicion,entradas_previas
0,100033926124811452,23.000000,0.000000,2.132530,0.0
1,1000400432115255220,21.615385,0.935144,0.111843,1.0
2,1001123163431776865,21.795918,0.785949,0.070691,68.0
3,1001144380199556647,22.016760,0.837833,0.633978,78.0
4,1001358436431521709,21.903226,0.970207,0.152169,0.0
5,1001650136929210538,22.031866,0.830947,0.000563,1479.0
6,1001893648440705480,22.562500,0.500000,1.695995,73.0
7,1002004782572506858,21.970228,0.652248,0.146664,150.0
8,1002085736203824817,22.272727,0.694284,0.047673,8.0
9,1002447145227437936,22.115499,0.813356,0.040113,550.0
10,1002862509106471090,22.347267,0.728389,0.006809,695.0
11,1003038576428296315,23.000000,0.000000,2.253057,17.0
12,1003279313141612495,22.894737,0.315302,1.615052,0.0
13,1003855069948308769,22.370031,0.483552,1.005857,5.0
14,1004535879545899547,23.000000,0.000000,2.945440,3.0
15,1004700862144409340,22.149733,0.357287,1.244064,0.0
16,1004741910852937385,22.837209,0.371340,1.732339,0.0
17,1004742301877775554,22.500000,0.518875,1.779522,4.0
18,1004800149279553387,22.083146,0.636579,0.017838,528.0
19,1005054093755188636,23.000000,0.000000,2.800609,0.0
20,1005228501295042451,22.142857,0.358569,1.014115,1.0
21,1005306798897590259,23.000000,0.000000,2.942633,0.0
22,100543418029071977,22.125000,0.612372,0.121585,8.0
23,1005862257005415556,22.037500,0.753788,0.349630,51.0
24,1005869594080353226,21.823529,0.833473,0.144323,86.0
25,1006047336388488529,21.327935,0.663929,0.108529,54.0
26,1006386733075661409,22.402062,0.613489,0.953585,0.0
27,1006635159741148154,21.222535,0.550859,0.009283,57.0
28,1006688297714348969,22.934866,0.247236,1.984624,7.0
29,1006797402765614581,21.812500,0.990030,0.057348,45.0
...,...,...,...,...,...
472789,8463819022493405594,22.000000,0.000000,1.910634,0.0
472815,120066053544397299,22.000000,0.000000,1.101404,0.0
472822,1675465894456303904,22.000000,0.000000,1.296024,0.0
472825,1808914933107929388,22.000000,0.000000,1.115675,0.0
472848,3237282560961568132,22.000000,0.000000,1.462977,0.0
472857,4480418618087428655,22.000000,0.000000,1.777397,0.0
472867,5162917905135447805,22.000000,0.000000,1.569112,0.0
473382,1091911987149783821,23.000000,0.000000,2.246217,0.0
473428,4389700610314188729,23.000000,0.000000,2.802441,0.0
473430,4448465669266609869,23.000000,0.000000,2.112555,0.0
473480,817713062634440208,23.000000,0.000000,2.809429,0.0
473504,2154190506951957785,21.000000,0.000000,0.815146,0.0
473528,3673380501301167226,23.000000,0.000000,2.122695,0.0
473536,4174230555993324923,21.000000,0.000000,0.817787,0.0
473561,6338388692042622627,23.000000,0.000000,2.686098,0.0
473593,8354412565619928900,21.000000,0.000000,0.917447,0.0
473630,2875991245911166305,21.000000,0.000000,0.691637,0.0
473684,7046018604591284421,22.000000,0.000000,1.884480,0.0
473720,1127100346799212752,22.000000,0.000000,1.032365,0.0
473727,1311021507745710058,22.000000,0.000000,1.080603,0.0
473737,1944593511424495249,22.000000,0.000000,1.653106,0.0
473743,2519711926042368334,22.000000,0.000000,1.030668,0.0
473747,2733151881632131754,22.000000,0.000000,1.429489,0.0
473784,4689245893119354457,22.000000,0.000000,1.850088,0.0
473801,5717468255227731540,22.000000,0.000000,1.010283,0.0
473816,6532569181386617584,22.000000,0.000000,1.197555,0.0
475059,5811542591767694512,23.000000,0.000000,2.519153,0.0
475118,1525572494050423197,23.000000,0.000000,2.033734,0.0
475129,2196302881459117962,23.000000,0.000000,2.106825,0.0
475148,3927025339438948829,23.000000,0.000000,2.205814,0.0

In [20]:
fecha_minima=pd.to_datetime('2019-04-22 00:00:00')
fecha_tope=pd.to_datetime('2019-04-25 00:00:00')

auctions_ventana3=auctions.loc[((auctions['date']>fecha_minima) & (auctions['date']<fecha_tope) )].copy(deep=False)
#la division es para pasar la diferencia de tiempso de timedelta a float de dias
auctions_ventana3['tiempo_hasta_aparicion']=(auctions_ventana2['date']-fecha_minima)/ np.timedelta64(24, 'h')
auctions_ventana3['dia_mean']=auctions_ventana3['date'].dt.day
auctions_ventana3['dia_desvio_std']=auctions_ventana3['date'].dt.day
auctions_ventana3.head(25)
auctions_ventana1_reducido=auctions_ventana1.groupby(['device_id']).agg({"dia_mean" : np.mean,\
                                                                         "dia_desvio_std" : "std",\
                                                                         'tiempo_hasta_aparicion':"min",\
                                                                        'entradas_previas':min})\
                                                                            .reset_index('device_id')
#entradas previas no se debe usar para predecir en esta ventana, sino para                
auctions_ventana1_reducido.dropna()

,date,device_id,ref_type_id,source_id,entradas_previas,tiempo_hasta_aparicion,dia_mean,dia_desvio_std
25108684,2019-04-22 00:00:00.017842,3258381879961405775,1,0,105,2.065046e-07,22,22
29857955,2019-04-22 00:00:00.061648,4439408176817895343,7,1,541,7.135185e-07,22,22
15836239,2019-04-22 00:00:00.068298,6979533046694728978,1,1,92,7.904861e-07,22,22
35521924,2019-04-22 00:00:00.068888,5640959168804437141,1,1,223,7.973148e-07,22,22
44041829,2019-04-22 00:00:00.086176,6570269971268216479,1,1,1576,9.974074e-07,22,22
37398961,2019-04-22 00:00:00.106517,7521944193832712399,1,3,30,1.232836e-06,22,22
25101683,2019-04-22 00:00:00.109681,7656576620964598366,1,1,260,1.269456e-06,22,22
15855075,2019-04-22 00:00:00.114217,2167579787675188862,1,3,1049,1.321956e-06,22,22
34292714,2019-04-22 00:00:00.117986,7521944193832712399,1,3,31,1.365579e-06,22,22
845031,2019-04-22 00:00:00.171364,7868371065416083239,1,6,161,1.983380e-06,22,22
10304057,2019-04-22 00:00:00.182189,1818814191191256852,1,1,347,2.108669e-06,22,22
27128088,2019-04-22 00:00:00.220263,8682809962690039620,1,0,1,2.549340e-06,22,22
23448920,2019-04-22 00:00:00.235686,1171537846855747403,7,8,250,2.727847e-06,22,22
35521925,2019-04-22 00:00:00.245625,7656576620964598366,1,1,261,2.842882e-06,22,22
44996388,2019-04-22 00:00:00.269586,7432147327103512777,1,1,415,3.120208e-06,22,22
38834928,2019-04-22 00:00:00.281653,7907011736232946600,1,0,204,3.259873e-06,22,22
34292715,2019-04-22 00:00:00.303598,1372179426442805233,1,5,633,3.513866e-06,22,22
25108685,2019-04-22 00:00:00.311511,1669324028654420995,1,0,44,3.605451e-06,22,22
46082751,2019-04-22 00:00:00.318767,1242706582918010871,1,0,58,3.689433e-06,22,22
44996389,2019-04-22 00:00:00.331514,8269813940194538674,1,1,1122,3.836968e-06,22,22
44041830,2019-04-22 00:00:00.344500,4497555628253712622,1,1,205,3.987269e-06,22,22
15867049,2019-04-22 00:00:00.346479,2504239618153784068,1,3,1288,4.010174e-06,22,22
33254778,2019-04-22 00:00:00.374027,3764718527532011034,7,6,8,4.329016e-06,22,22
839461,2019-04-22 00:00:00.375952,615660211215927742,1,3,1608,4.351296e-06,22,22
825527,2019-04-22 00:00:00.376950,4736639153753890520,1,0,1317,4.362847e-06,22,22

In [21]:
fecha_minima=pd.to_datetime('2019-04-23 00:00:00')
fecha_tope=pd.to_datetime('2019-04-26 00:00:00')

auctions_ventana4=auctions.loc[((auctions['date']>fecha_minima) & (auctions['date']<fecha_tope) )].copy(deep=False)
#la division es para pasar la diferencia de tiempso de timedelta a float de dias
auctions_ventana4['tiempo_hasta_aparicion']=(auctions_ventana2['date']-fecha_minima)/ np.timedelta64(24, 'h')
auctions_ventana4['dia_mean']=auctions_ventana4['date'].dt.day
auctions_ventana4['dia_desvio_std']=auctions_ventana4['date'].dt.day
auctions_ventana4.head(25)
auctions_ventana1_reducido=auctions_ventana1.groupby(['device_id']).agg({"dia_mean" : np.mean,\
                                                                         "dia_desvio_std" : "std",\
                                                                         'tiempo_hasta_aparicion':"min",\
                                                                        'entradas_previas':min})\
                                                                            .reset_index('device_id')
#entradas previas no se debe usar para predecir en esta ventana, sino para                
auctions_ventana1_reducido.dropna()

,date,device_id,ref_type_id,source_id,entradas_previas,tiempo_hasta_aparicion,dia_mean,dia_desvio_std
29533754,2019-04-23 00:00:00.006034,1538918413502116969,7,0,7,6.983796e-08,23,23
1189926,2019-04-23 00:00:00.030241,600082216555821116,1,8,53,3.500116e-07,23,23
13469754,2019-04-23 00:00:00.044646,815049142052275764,1,0,282,5.167361e-07,23,23
25915736,2019-04-23 00:00:00.058370,4671020307442338587,1,1,1001,6.755787e-07,23,23
25912376,2019-04-23 00:00:00.079831,2451977314641800014,1,1,223,9.239699e-07,23,23
134889,2019-04-23 00:00:00.091860,1337539488241862777,1,1,5406,1.063194e-06,23,23
44844946,2019-04-23 00:00:00.097058,7481149659173762953,1,3,1106,1.123356e-06,23,23
42899212,2019-04-23 00:00:00.098743,5922395495132656512,1,0,12,1.142859e-06,23,23
7508800,2019-04-23 00:00:00.105470,5742662260721642176,1,1,185,1.220718e-06,23,23
149155,2019-04-23 00:00:00.108275,2888987082666903234,1,3,35,1.253183e-06,23,23
25908499,2019-04-23 00:00:00.111511,8576802944381780454,1,1,2456,1.290637e-06,23,23
15206642,2019-04-23 00:00:00.119918,2537742784360706377,7,3,457,1.387940e-06,23,23
25915737,2019-04-23 00:00:00.120882,5609264760822938023,1,1,14,1.399097e-06,23,23
45795578,2019-04-23 00:00:00.124153,226980245221465250,7,1,507,1.436956e-06,23,23
44867096,2019-04-23 00:00:00.145745,1714560103973477883,1,1,54,1.686863e-06,23,23
25912015,2019-04-23 00:00:00.149505,8702245411877737854,1,1,143,1.730382e-06,23,23
44830603,2019-04-23 00:00:00.169625,2147598797231096703,1,1,65,1.963252e-06,23,23
25630930,2019-04-23 00:00:00.170930,4909643650527478921,1,0,142,1.978356e-06,23,23
29530698,2019-04-23 00:00:00.174224,4460709521984866489,7,4,43,2.016481e-06,23,23
42900851,2019-04-23 00:00:00.181767,5742662260721642176,1,6,186,2.103785e-06,23,23
7499794,2019-04-23 00:00:00.185428,1092991678453026907,1,3,138,2.146157e-06,23,23
36645943,2019-04-23 00:00:00.189436,4723260946174451877,1,1,68,2.192546e-06,23,23
45809432,2019-04-23 00:00:00.196218,7822641539002091645,1,0,23,2.271042e-06,23,23
42899213,2019-04-23 00:00:00.202923,5255697018871139897,1,0,342,2.348646e-06,23,23
147586,2019-04-23 00:00:00.227557,2970983774671628816,1,6,171,2.633762e-06,23,23

In [22]:
fecha_minima=pd.to_datetime('2019-04-24 00:00:00')
fecha_tope=pd.to_datetime('2019-04-27 00:00:00')

auctions_ventana5=auctions.loc[((auctions['date']>fecha_minima) & (auctions['date']<fecha_tope) )].copy(deep=False)
#la division es para pasar la diferencia de tiempso de timedelta a float de dias
auctions_ventana5['tiempo_hasta_aparicion']=(auctions_ventana2['date']-fecha_minima)/ np.timedelta64(24, 'h')
auctions_ventana5['dia_mean']=auctions_ventana5['date'].dt.day
auctions_ventana5['dia_desvio_std']=auctions_ventana5['date'].dt.day
auctions_ventana5.head(25)
auctions_ventana1_reducido=auctions_ventana1.groupby(['device_id']).agg({"dia_mean" : np.mean,\
                                                                         "dia_desvio_std" : "std",\
                                                                         'tiempo_hasta_aparicion':"min",\
                                                                        'entradas_previas':min})\
                                                                            .reset_index('device_id')
#entradas previas no se debe usar para predecir en esta ventana, sino para                
auctions_ventana1_reducido.dropna()

,date,device_id,ref_type_id,source_id,entradas_previas,tiempo_hasta_aparicion,dia_mean,dia_desvio_std
20776038,2019-04-24 00:00:00.015206,4962177571260097630,1,1,16049,NaN,24,24
20775706,2019-04-24 00:00:00.016556,6854070487213255676,7,1,921,NaN,24,24
15520571,2019-04-24 00:00:00.019373,6028134205740110035,1,1,4254,NaN,24,24
16921784,2019-04-24 00:00:00.043372,8598596355049388965,1,3,720,NaN,24,24
46245814,2019-04-24 00:00:00.044957,5420144902280053407,1,1,335,NaN,24,24
34723006,2019-04-24 00:00:00.051597,8598596355049388965,1,3,721,NaN,24,24
16921785,2019-04-24 00:00:00.056784,8598596355049388965,1,3,722,NaN,24,24
20776039,2019-04-24 00:00:00.063860,9136120756615151076,7,1,87,NaN,24,24
15520572,2019-04-24 00:00:00.102667,3291150659957937068,1,1,11067,NaN,24,24
34723007,2019-04-24 00:00:00.108174,8598596355049388965,1,5,723,NaN,24,24
20776040,2019-04-24 00:00:00.111698,8161874759802909326,1,1,651,NaN,24,24
17275326,2019-04-24 00:00:00.121254,4604444942782694045,1,1,342,NaN,24,24
18941354,2019-04-24 00:00:00.123221,4823409427130502368,1,0,458,NaN,24,24
18396766,2019-04-24 00:00:00.131443,5969440185172603266,1,3,858,NaN,24,24
4469436,2019-04-24 00:00:00.135185,2950232437133171952,1,1,916,NaN,24,24
7800051,2019-04-24 00:00:00.148138,4007475754558605810,1,1,4076,NaN,24,24
18393484,2019-04-24 00:00:00.164630,4789157436338910788,1,1,65,NaN,24,24
18393485,2019-04-24 00:00:00.232246,6936706560282909755,1,1,21,NaN,24,24
4821762,2019-04-24 00:00:00.235233,2845521603875630350,1,0,85,NaN,24,24
20775707,2019-04-24 00:00:00.282754,8010782364621477946,1,1,4625,NaN,24,24
43045410,2019-04-24 00:00:00.283510,2106092803481807151,1,1,210,NaN,24,24
11478382,2019-04-24 00:00:00.284550,1458854160686138675,1,6,667,NaN,24,24
21456921,2019-04-24 00:00:00.302590,6825841554212314809,1,0,130,NaN,24,24
7787408,2019-04-24 00:00:00.305919,7732120761640815524,1,0,985,NaN,24,24
9914985,2019-04-24 00:00:00.321566,1115340971387237632,1,1,958,NaN,24,24